hpc<- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
library(dplyr)
hpc<- hpc %>%
  filter(hpc$Date == "1/2/2007" | hpc$Date == "2/2/2007")
hpc$Date<- as.Date(hpc$Date, "%d/%m/%Y")
library(tidyr)
hpc <- unite(hpc, col = "DateTime", c("Date", "Time"), sep =  " ")
hpc$DateTime<- strptime(hpc$DateTime, format = "%Y-%m-%d %H:%M:%S")
hpc$Sub_metering_1 <-as.character(hpc$Sub_metering_1)
hpc$Sub_metering_1 <-as.numeric(hpc$Sub_metering_1)
hpc$Sub_metering_2 <-as.character(hpc$Sub_metering_2)
hpc$Sub_metering_2 <-as.numeric(hpc$Sub_metering_2)
hpc$Sub_metering_3 <-as.character(hpc$Sub_metering_3)
hpc$Sub_metering_3 <-as.numeric(hpc$Sub_metering_3)
hpc$Voltage <-as.character(hpc$Voltage)
hpc$Voltage <-as.numeric(hpc$Voltage)
hpc$Global_reactive_power <-as.character(hpc$Global_reactive_power)
hpc$Global_reactive_power<-as.numeric(hpc$Global_reactive_power)
Sys.setlocale("LC_TIME","English")
par(mfrow = c(2,2))
plot(hpc$DateTime, hpc$Global_active_power, type = "n",xlab = "", ylab = "Global Active Power")
lines(hpc$DateTime, hpc$Global_active_power)
plot(hpc$DateTime, hpc$Voltage, type = "n", xlab = "datetime")
lines(hpc$DateTime, hpc$Voltage, ylab ="Voltage")
with(hpc, plot(DateTime, Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering"))
lines(hpc$DateTime, hpc$Sub_metering_1)
lines(hpc$DateTime, hpc$Sub_metering_2, col = "red")
lines(hpc$DateTime, hpc$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"), lty = c(1,1,1),
       legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(hpc$DateTime, hpc$Global_reactive_power, type = "n", xlab = "datetime", ylab = "Global_reactive_power")
lines(hpc$DateTime, hpc$Global_reactive_power)
